# 2.配置相关信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?ServerTimezone=UTC
    username: root
    password: Wch@0817
# 3.设置mp相关配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
  configuration:
    map-underscore-to-camel-case: true
