person:
  userName: 张三
  boss: true
  birth: 2019/12/9
  age: 15
  #  interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
  animal:
    - 阿猫
    - 阿狗
#  score:
#    - 英语: 80
#    - 数学: 90
  score: { english: 80,math: 90 }
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 阿狗
    weight: 12
  allPets:
    sick:
      - { name: 阿狗,weight: 12 }
    health:
      - name: 阿猫
        weight: 14
      - name: 阿虫
        weight: 15