package pers.rain.bean;

public class TBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_id
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_name
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.price
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.stock
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_id
     *
     * @return the value of t_book.book_id
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_id
     *
     * @param bookId the value for t_book.book_id
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_name
     *
     * @return the value of t_book.book_name
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_name
     *
     * @param bookName the value for t_book.book_name
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.price
     *
     * @return the value of t_book.price
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.price
     *
     * @param price the value for t_book.price
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.stock
     *
     * @return the value of t_book.stock
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.stock
     *
     * @param stock the value for t_book.stock
     *
     * @mbggenerated Fri Nov 25 20:52:54 CST 2022
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}